
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar'
import App from '@/components/App'
import StoreProvider from '@/components/redux/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export const metadata = {
  title: {
    default: 'Next APP Home',
    template: '%s | NEXT JS 14'
  },
  description: 'next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body className={inter.className}>       
        <StoreProvider>
        <NavBar />
        <App>{children}</App>
        </StoreProvider>       
        {/* <Footer /> */}
      </body>
    </html>
  )
}
